name: release

on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - target: x86_64-pc-windows-gnu
          #   archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          # - target: x86_64-apple-darwin
          #   archive: zip
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}